version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region us-central1 | docker login --username AWS --password-stdin 727646474370.dkr.ecr.us-central1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t 727646474370.dkr.ecr.us-central1.amazonaws.com/anitha-image:${CODEBUILD_RESOLVED_SOURCE_VERSION} .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 727646474370.dkr.ecr.us-central1.amazonaws.com/anitha-image:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'

